recipient: backup@bitfication.com
ftp_servers:
  server1:
    host: ftp.bitfication.com
    username: user
    password: pass
  server2:
    host: ftp2.bitfication.com
    username: user
    password: pass
