production:
  adapter: mysql2
  encoding: utf8
  database: bitficproddb
  username: bitficprodusr
  password: bitficpass
  host: localhost

development:
  adapter: mysql2
  encoding: utf8
  database: bitficdevdb
  username: bitficdevusr
  password: bitficpass
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: bitfictestdb
  username: bitfictstusr
  password: bitficpass
  host: localhost
